[package]
name = "a"
version = "0.1.0"
authors = ["ntegan"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.19"
cpio = "0.2.0"
